AWSTemplateFormatVersion: "2010-09-09"
Description: Create

Parameters:
  myVPC:
    Description: VPC to deploy the services
    Type: AWS::EC2::VPC::Id

  ServerSubnet:
    Description: Subnet to be used for our Web Server
    Type: AWS::EC2::Subnet::Id

  AMItoUse:
    Description: AMI to use for our base image
    Type: String

Resources:

  RoleForSSMAccess:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  ServerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref RoleForSSMAccess

  WebAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to the host
      VpcId:
        !Ref myVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

  ServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMItoUse
      InstanceType: t3.micro
      IamInstanceProfile: !Ref ServerInstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet:
            - !Ref WebAccessSecurityGroup
          SubnetId: !Ref ServerSubnet
